Repository RominaSolHaag/E1-aula13, pull requests merged in 2022-08, with the labels that each got.

#37 Add files via upload
  basededatosISPC.sql
Labels: DATA BASE

#51 Ejercicios de python Romina
  Ejercicio123romi.py
Labels: Pitón

#53 Cv ari
  ej1_ej2_ej7.sql
  ej5_tuplas.py
Labels: DATA BASE, Pitón

#55 Cv romi
  Perro.sql
Labels: DATA BASE

#61 Se creo una nueva rama ya que no pudimos resolver los conflctos de cvDouglas…
  ISCPDouglas.sql
  ejercicio7.py
Labels: DATA BASE, Python
